apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app.kubernetes.io/name: test
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test
    spec:
      containers:
        - name: test
          image: docker.io/michalpalkowski/test:latest
          envFrom:
            - secretRef:
                name: secret
            - configMapRef:
                name: config
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  selector:
    app.kubernetes.io/name: test
  ports:
    - name: tcp
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: udp
      protocol: UDP
      port: 80
      targetPort: 3000
