apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: test
spec:
  parentRefs:
    - kind: Gateway
      name: nginx
      namespace: nginx-gateway
  hostnames:
    - test.visoft.dev
  rules:
    - matches:
      backendRefs:
        - name: test
          port: 80
